name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # optional:
          pip install pytest pytest-cov flake8

      - name: Lint
        run: flake8 . || true   # set to fail the build by removing "|| true" later

      - name: Tests
        run: pytest -q
